q5name = lab8c_shmb8fork
q2name = lab8c_shm2client
q3name = lab8c_shm3client

q5:
	gcc ${q5name}.c -o ${q5name} && ./${q5name}

q2:
	gcc ${q2name}.c -o ${q2name} && ./${q2name}

q3:
	gcc ${q3name}.c -o ${q3name} && ./${q3name}